### Permutation Test R Code

fired <- c(34, 37, 37, 38, 41, 42, 43, 44, 44, 45, 45, 45, 46, 48, 49, 53, 53, 54, 54, 55, 56)
not.fired <- c(27, 33, 36, 37, 38, 38, 39, 42, 42, 43, 43, 44, 44, 44, 45, 45, 45, 45, 46, 46, 47, 47, 48, 48, 49, 49, 51, 51, 52, 54)
label1 <- rep('fired', 21)
label2 <- rep('not.fired', 30)
label.all <- as.factor(c(label1, label2))

samoa <- data.frame(status=label.all, age=c(fired, not.fired))



t.test(age ~ status, data=samoa, var.equal=TRUE)\

number_of_permutations <- 1000
xbarholder <- numeric(0)
counter <- 0
observed_diff <- mean(subset(samoa, status == "fired")$age)-mean(subset(samoa, status == "not.fired")$age)

set.seed(123)
for(i in 1:number_of_permutations)
{
scramble <- sample(samoa$age, 51)
fired.new <- scramble[1:21]
not.fired.new <- scramble[22:51]
diff <- mean(fired.new)-mean(not.fired.new)
xbarholder[i] <- diff
## if doing a two-sided t-test, the following line should be (abs(diff) > abs(observed_diff))
if(diff > observed_diff)
counter <- counter + 1
}
hist(xbarholder, xlab='Permuted Fired - Not Fired', main='Histogram of Permuted Mean Differences')
box()

pvalue <- counter / number_of_permutations
pvalue
## [1] 0.133

### Permutation Code SAS
data creativity;                                                                                                                           
input treatment score;   /* 1 is extrinsic and 0 in intrinsic*/                                                                                                                                                                                                     
datalines;                                                                                                                                                                                                                   
1 5
1 5.4
1 6.1
1 10.9
1 11.8
1 12
1 12.3
1 14.8
1 15
1 16.8
1 17.2
1 17.2
1 17.4
1 17.5
1 18.5
1 18.7
1 18.7
1 19.2
1 19.5
1 20.7
1 21.2
1 22.1
1 24
0 12
0 12
0 12.9
0 13.6
0 16.6
0 17.2
0 17.5
0 18.2
0 19.1
0 19.3
0 19.8
0 20.3
0 20.5
0 20.6
0 21.3
0 21.6
0 22.1
0 22.2
0 22.6
0 23.1
0 24
0 24.3
0 26.7
0 29.7
;                                                                                                                                                                                                                            
                                                                                                                                                                                                                             
* To get the observed difference;                                                                                                                                                                                            
proc ttest data=creativity;  * You will need to change the dataset name here.;                                                                                                                                                     
                                                                                                                                                                                                                             
   class treatment;    *and change the class variable to match yours here;                                                                                                                                                  
                                                                                                                                                                                                                             
   var score;          * and change the var name here.;                                                                                                                                                                      
                                                                                                                                                                                                                             
run;                                                                                                                                                                                                                         

ods output off;
ods exclude all;
                                                                                                                                                                                                                         
*borrowed code from internet ... randomizes observations and creates a matrix ... one row per randomization ;                                                                                                                
proc iml;                                                                                                                                                                                                                    
use creativity;                        * change data set name here to match your data set name above;                                                                                                                              
read all var{treatment score} into x;   *change varibale names here ... make sure it is class then var ... in that order.;                                                                                                  
p = t(ranperm(x[,2],10000));    *Note that the "1000" here is the number of permutations. ;                                                                                                                                    
paf = x[,1]||p;                                                                                                                                                                                                              
create newds from paf;                                                                                                                                                                                                       
append from paf;                                                                                                                                                                                                             
quit;                                                                                                                                                                                                                        
                                                                                                                                                                                                                             
*calculates differences and creates a histogram;                                                                                                                                                                             
ods output conflimits=diff;                                                                                                                                                                                                  
proc ttest data=newds plots=none;                                                                                                                                                                                            
  class col1;                                                                                                                                                                                                                
  var col2 - col10001;                                                                                                                                                                                                        
run;                                                                                                                                                                                                                         

ods output on;
ods exclude none;       
                  
proc univariate data=diff;                                                                                                                                                                                                   
  where method = "Pooled";                                                                                                                                                                                                   
  var mean;                                                                                                                                                                                                                  
  histogram mean;                                                                                                                                                                                                            
run;                                                                                                                                                                                                                         
                                                                                                                                                                                  
*The code below calculates the number of randomly generated differences that are as extreme or more extreme thant the one observed (divide this number by 1000 you have the pvalue);                                         
*check the log to see how many observations are in the data set.... divide this by 1000 (or however many permutations you generated) and that is the (one sided)p-value;                                                     
data numdiffs;                                                                                                                                                                                                               
set diff;                                                                                                                                                                                                                    
where method = "Pooled";                                                                                                                                                                                                     
if abs(mean) >= 4.1442;   *you will need to put the observed difference you got from t test above here.  note if you have a one or two tailed test.;                                                                           
run;                                                                                                                                                                                                                         
* just a visual of the rows produced ... you can get the number of obersvations from the last data step and the Log window.;                                                                                                 
proc print data = numdiffs;                                                                                                                                                                                                  
where method = "Pooled";                                                                                                                                                                                                     
run;                                                                                                                                                                                                                         
                                                                                                                                                                                                                             
                                                                                                                                                                                                                          
*Idea from http://sas-and-r.blogspot.com/2011/10/example-912-simpler-ways-to-carry-out.html ;      
